# Site settings
title: Gaussian Process Summer School, 2015
author:
  email: 
description: > # this means to ignore newlines until "baseurl:"
  The 2015 Gaussian Process Summer School held at the University of Sheffield.
baseurl: "/gpss15" # the subpath of your site, e.g. /blog/
url: "https://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  gpschool
facebook_page: gaussianprocesssummerschool

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: gpschool/jekyll-theme
style: gpss

youtube:
  height: 315
  width: 560

ghub:
  edit: true
  repository: gpss15

markdown: kramdown

# Build settings
future: true

permalink: "/:categories/:title.html"

analytics:
  google:
    tracking_id: UA-62991754-1 

conference:
  draft: False
  hide_tentative: True
  short_name: GPSS
  full_name: Gaussian Process Summer School
  location: Pam Liversidge Building, PLB-E05, University of Sheffield, UK
  name: Gaussian Process Summer School
  year: 2015
  month: September
  dates:
  - 2015-09-14
  - 2015-09-15
  - 2015-09-16
  - 2015-09-17
  chairs:
  - type: Organizers
    people: 
    - {given: Neil, family: Lawrence, url: "https://inverseprobability.com"}
    - {given: Javier, family: Gonzalez, url: "https://javiergonzalezh.github.io/"}
    - {given: Sheffield ML Group, url: "https://sheffieldml.github.io"}
    
previous_meeting:
  name: GPSS 2014
  url: "https://gpss.cc/gpss14
  
 

