# Site settings
title: Gaussian Process Summer School, 2015
author:
  email: 
description: > # this means to ignore newlines until "baseurl:"
  The 2015 Gaussian Process Summer School held at the University of Sheffield.
baseurl: "/gpss15" # the subpath of your site, e.g. /blog/
url: "https://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  gpschool
facebook_page: gaussianprocesssummerschool

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: gpschool/jekyll-theme
style: gpss


analytics:
  google:
    tracking_id: UA-62991754-1

youtube:
  height: 315
  width: 560

conference:
  hosts:
  chairs:
  - type:
    people: 
    - {given: Neil, family: Lawrence, url: "http://inverseprobability.com"}
    - {given: Javier, family: Gonzalez, url: "http://javiergonzalezh.github.io/"}
    - {given: Sheffield ML Group, url: "http://sheffieldml.github.io"}
  name: Gaussian Process Summer School
  short_name: GPSS
  full_name: Gaussian Process Summer School
  location: Pam Liversidge Building, PLB-E05, University of Sheffield, UK
  year: 2015
  month: September
  dates:
  - 2015-07-14
  - 2015-07-15
  - 2015-07-16
  - 2015-07-17
  draft: Y # set to Y if the programme is draft only.


previous_meeting:
  name: GPSS 2014
  url: "https://gpss.cc/gpss14"

# Build settings
markdown: kramdown

